#!/bin/bash

DB_FIELD='DB_DATABASE='
DB_PATH="$(pwd)/database/db.sqlite"

composer install
npm install
cp .env.example .env
touch database/db.sqlite
sed -i '14d' .env
sed -i "13 a $DB_FIELD$DB_PATH" .env
php artisan key:generate
php artisan migrate
cp auth_mod/AuthenticatesUsers.php vendor/laravel/ui/auth-backend/
cp auth_mod/RegistersUsers.php vendor/laravel/ui/auth-backend/

